#!/bin/bash

FAF_DATA_DIR=/tmp/faf-docker
FAF_HTTP_PORT=8888
IMAGE_NAME=mbrysa/faf:fedora

DR="sudo docker run -p $FAF_HTTP_PORT:80 -i -t -v $FAF_DATA_DIR/pgsql:/var/lib/pgsql -v $FAF_DATA_DIR/faf:/var/spool/faf $IMAGE_NAME"
