#!/bin/bash
# Initializes faf's storage and PostgreSQL db

source config

mkdir $FAF_DATA_DIR/pgsql
mkdir $FAF_DATA_DIR/faf
$DR bash -c "mkdir /var/lib/pgsql/data;
chown postgres:postgres /var/lib/pgsql/data;
sudo -u postgres /usr/bin/pg_ctl initdb -D /var/lib/pgsql/data;
mkdir /var/spool/faf/reports /var/spool/faf/reports/incoming /var/spool/faf/reports/saved /var/spool/faf/reports/deferred /var/spool/faf/lob;
chown -R faf:faf /var/spool/faf;
sudo -u postgres /usr/bin/pg_ctl start -D /var/lib/pgsql/data -w;
sudo -u postgres psql -c \"CREATE USER faf;\";
sudo -u postgres psql -c \"CREATE DATABASE faf;\";
sudo -u postgres psql -c \"GRANT ALL PRIVILEGES ON DATABASE faf TO faf;\";
sudo -u postgres psql -d faf -c \"CREATE EXTENSION semver;\";
sudo -u faf faf-migrate-db --create-all;
sudo -u faf faf-migrate-db --stamp-only;
sudo -u faf faf init;
"
echo -e "Recommended now:\n $ ./faf-action pull-releases -o fedora -vd\n $ ./faf-action pull-releases -o centos -vd"
echo -e "Add different Operating system releases like:\n ./faf-action releaseadd -o rhel --opsys-release '7.0'"
