#!/bin/bash
# Gets added to the image

sudo -u postgres /usr/bin/pg_ctl start -D /var/lib/pgsql/data -w
crond
/usr/sbin/httpd

while [ $? == 0 ] ; do sleep 999999999999 ; done

sudo -u postgres /usr/bin/pg_ctl stop -D /var/lib/pgsql/data
